//const {} = require('./consts.js')

module.exports = {
	record_mode: [
		{ id: '00', label: 'Record' },
		{ id: '01', label: 'Record Pause' },
		{ id: '02', label: 'Take Split' },
	],
	search_mode: [
		{ id: '00', label: 'Forward - Normal' },
		{ id: '01', label: 'Reverse - Normal' },
		{ id: '10', label: 'Forward - High' },
		{ id: '11', label: 'Reverse - High' },
	],
	skip_mode: [
		{ id: '00', label: 'Track Skip Next' },
		{ id: '01', label: 'Track Skip Previous' },
		{ id: '20', label: 'Mark Skip Next' },
		{ id: '21', label: 'Mark Skip Previous' },
	],
	repeat_mode: [
		{ id: '00', label: 'Repeat Off' },
		{ id: '01', label: 'Repeat Normal' },
		{ id: '21', label: 'Repeat Vamping' },
		{ id: 'FF', label: 'Sense' },
	],
	remoteLocal_mode: [
		{ id: '00', label: 'Remote' },
		{ id: '01', label: 'Local' },
		{ id: 'FF', label: 'Sense' },
	],
	play_mode: [
		{ id: '00', label: 'All Take' },
		{ id: '01', label: 'One Take' },
	],
	currentTrackTime_sense: [
		{ id: '10', label: 'Elapsed Time' },
		{ id: '11', label: 'Remain Time' },
		{ id: '12', label: 'Total Elapsed Time' },
		{ id: '13', label: 'Total Remain Time' },
		{ id: '14', label: 'Timecode Time' },
	],
	projectSkip_mode: [
		{ id: '00', label: 'Project Next' },
		{ id: '01', label: 'Project Previous' },
	],
	chase_mode: [
		{ id: '00', label: 'Chase OFF' },
		{ id: '01', label: 'Chase ON' },
		{ id: 'FF', label: 'Sense' },
	],
	tcGeneratorSelect_mode: [
		{ id: '00', label: 'Free Run' },
		{ id: '01', label: 'Free Once' },
		{ id: '02', label: 'Time Of Day' },
		{ id: '03', label: 'Jam Sync' },
		{ id: '04', label: 'Regen' },
		{ id: '05', label: 'Rec Run' },
		{ id: '06', label: 'TC Sync Rec' },
		{ id: 'FF', label: 'Sense' },
	],
	tcFrameTypeSelect_mode: [
		{ id: '23', label: '23.976F' },
		{ id: '24', label: '24F' },
		{ id: '25', label: '25F' },
		{ id: '29DF', label: '29.97DF' },
		{ id: '29', label: '29.97NDF' },
		{ id: '30DF', label: '30DF' },
		{ id: '30', label: '30NDF' },
		{ id: 'FF', label: 'Sense' },
	],
	tcOutputSelect_mode: [
		{ id: '00', label: 'Internal' },
		{ id: '01', label: 'Word' },
		{ id: '02', label: 'Video' },
		{ id: '03', label: 'Slot 1' },
		{ id: '04', label: 'Slot 2' },
		{ id: 'FF', label: 'Sense' },
	],
	wordThruSelect_mode: [
		{ id: '00', label: 'WORD OUT/TERM ON' },
		{ id: '01', label: 'WORD OUT/TERM OFF' },
		{ id: '11', label: 'WORD THRU/TERM OFF' },
		{ id: 'FF', label: 'Sense' },
	],
	bitLengthSelect_mode: [
		{ id: '16', label: '16bit' },
		{ id: '24', label: '24bit' },
		{ id: 'FF', label: 'Sense' },
	],
	pause_mode: [
		{ id: '00', label: 'Split' },
		{ id: '01', label: 'No Split' },
		{ id: 'FF', label: 'Sense' },
	],
	audioOverMarketSelect_mode: [
		{ id: '00', label: 'Marker Off' },
		{ id: '01', label: 'Marker On' },
		{ id: 'FF', label: 'Sense' },
	],
	timeInternalMarkerSelect_mode: [
		{ id: '00', label: 'Marker Off' },
		{ id: '01', label: 'Marker On' },
		{ id: 'FF', label: 'Sense' },
	],
	syncUnlockMarkerSelect_mode: [
		{ id: '00', label: 'Marker Off' },
		{ id: '01', label: 'Marker On' },
		{ id: 'FF', label: 'Sense' },
	],
	recFsSelect_mode: [
		{ id: '440000', label: '44.1 kHz' },
		{ id: '480000', label: '48 kHz' },
		{ id: '880000', label: '88.2 kHz' },
		{ id: '960000', label: '96 kHz' },
		{ id: 'FF', label: 'Sense' },
	],
	fileNameSelect_mode: [
		{ id: '00', label: 'Date & Time' },
		{ id: '01', label: 'Folder' },
		{ id: '11', label: 'User Word' },
		{ id: 'FF', label: 'Sense' },
	],
	mediaRemainSense_mode: [
		{ id: '00', label: 'SSD' },
		{ id: '01', label: 'USB' },
	],
	mediaFormat_mode: [
		{ id: '0000', label: 'Quick Format: SSD' },
		{ id: '0100', label: 'Full Format: SSD' },
	],
	auxAssignKeySelect_auxKey: [
		{ id: '01', label: 'AUX 1' },
		{ id: '02', label: 'AUX 2' },
		{ id: '03', label: 'AUX 3' },
		{ id: '04', label: 'AUX 4' },
		{ id: '05', label: 'AUX 5' },
		{ id: '06', label: 'AUX 6' },
	],
	auxAssignKeySelect_function: [
		{ id: '00', label: 'PLAY/PAUSE' },
		{ id: '01', label: 'PAUSE' },
		{ id: '02', label: 'REC' },
		{ id: '03', label: 'FADER REC' },
		{ id: '04', label: 'FADER START' },
		{ id: '05', label: 'REW' },
		{ id: '06', label: 'F.FWD' },
		{ id: '07', label: 'TAKE SKIP-' },
		{ id: '08', label: 'TAKE SKIP+' },
		{ id: '09', label: 'MARK SKIP-' },
		{ id: '0A', label: 'MARK SKIP+' },
		{ id: '0B', label: 'TAKE/MARK SKIP-' },
		{ id: '0C', label: 'TAKE/MARK SKIP+' },
		{ id: '0D', label: 'MARK' },
		{ id: 'FF', label: 'Sense' },
	],
	auxAssignKeyTallySelect_auxKey: [
		{ id: '01', label: 'AUX 1' },
		{ id: '02', label: 'AUX 2' },
		{ id: '03', label: 'AUX 3' },
		{ id: '04', label: 'AUX 4' },
		{ id: '05', label: 'AUX 5' },
	],
	auxAssignKeyTallySelect_function: [
		{ id: '00', label: 'STOP' },
		{ id: '01', label: 'PLAY' },
		{ id: '02', label: 'PAUSE' },
		{ id: '03', label: 'REC' },
		{ id: '04', label: 'EOM' },
		{ id: '05', label: 'ERROR' },
		{ id: '06', label: 'EOM/ERROR' },
		{ id: 'FF', label: 'Sense' },
	],
	meterPeakHoldTimePreset_mode: [
		{ id: '00', label: 'Hold Time 0s' },
		{ id: '10', label: 'Hold Time 10s' },
		{ id: 'FE', label: 'Hold Time Inf.' },
		{ id: 'FF', label: 'Sense' },
	],
	digitalReferenceLevelPreset_mode: [
		{ id: '09', label: 'Reference Level - 9dB' },
		{ id: '14', label: 'Reference Level -14dB' },
		{ id: '16', label: 'Reference Level -16dB' },
		{ id: '18', label: 'Reference Level -18dB' },
		{ id: '20', label: 'Reference Level -20dB' },
		{ id: 'FF', label: 'Sense' },
	],
}
