//const {} = require('./consts.js')

module.exports = {
	record_mode: [
		{ id: '00', label: 'Record' },
		{ id: '01', label: 'Record Pause' },
		{ id: '02', label: 'Take Split' },
	],
	search_mode: [
		{ id: '00', label: 'Forward - Normal' },
		{ id: '01', label: 'Reverse - Normal' },
		{ id: '10', label: 'Forward - High' },
		{ id: '11', label: 'Reverse - High' },
	],
	skip_mode: [
		{ id: '00', label: 'Track Skip Next' },
		{ id: '01', label: 'Track Skip Previous' },
		{ id: '20', label: 'Mark Skip Next' },
		{ id: '21', label: 'Mark Skip Previous' },
	],
	repeat_mode: [
		{ id: '00', label: 'Repeat Off' },
		{ id: '01', label: 'Repeat Normal' },
		{ id: '21', label: 'Repeat Vamping' },
		{ id: 'FF', label: 'Sense' },
	],
	remoteLocal_mode: [
		{ id: '00', label: 'Remote' },
		{ id: '01', label: 'Local' },
		{ id: 'FF', label: 'Sense' },
	],
	play_mode: [
		{ id: '00', label: 'All Take' },
		{ id: '01', label: 'One Take' },
	],
	currentTrackTime_sense: [
		{ id: '10', label: 'Elapsed Time' },
		{ id: '11', label: 'Remain Time' },
		{ id: '12', label: 'Total Elapsed Time' },
		{ id: '13', label: 'Total Remain Time' },
		{ id: '14', label: 'Timecode Time' },
	],
	projectSkip_mode: [
		{ id: '00', label: 'Project Next' },
		{ id: '01', label: 'Project Previous' },
	],
	chase_mode: [
		{ id: '00', label: 'Chase OFF' },
		{ id: '01', label: 'Chase ON' },
		{ id: 'FF', label: 'Sense' },
	],
	tcGeneratorSelect_mode: [
		{ id: '00', label: 'Free Run' },
		{ id: '01', label: 'Free Once' },
		{ id: '02', label: 'Time Of Day' },
		{ id: '03', label: 'Jam Sync' },
		{ id: '04', label: 'Regen' },
		{ id: '05', label: 'Rec Run' },
		{ id: '06', label: 'TC Sync Rec' },
		{ id: 'FF', label: 'Sense' },
	],
	tcFrameTypeSelect_mode: [
		{ id: '23', label: '23.976F' },
		{ id: '24', label: '24F' },
		{ id: '25', label: '25F' },
		{ id: '29DF', label: '29.97DF' },
		{ id: '29', label: '29.97NDF' },
		{ id: '30DF', label: '30DF' },
		{ id: '30', label: '30NDF' },
		{ id: 'FF', label: 'Sense' },
	],
	tcOutputSelect_mode: [
		{ id: '00', label: 'Generator Out' },
		{ id: '01', label: 'Play Out' },
		{ id: 'FF', label: 'Sense' },
	],
	clockMasterSelect_mode: [
		{ id: '00', label: 'Internal' },
		{ id: '01', label: 'Word' },
		{ id: '02', label: 'Video' },
		{ id: '03', label: 'Slot 1' },
		{ id: '04', label: 'Slot 2' },
		{ id: 'FF', label: 'Sense' },
	],
	wordThruSelect_mode: [
		{ id: '00', label: 'WORD OUT/TERM ON' },
		{ id: '01', label: 'WORD OUT/TERM OFF' },
		{ id: '11', label: 'WORD THRU/TERM OFF' },
		{ id: 'FF', label: 'Sense' },
	],
	recordFunctionSelect_tracks: [
		{ id: 1, label: 'Track 1' },
		{ id: 2, label: 'Track 2' },
		{ id: 3, label: 'Track 3' },
		{ id: 4, label: 'Track 4' },
		{ id: 5, label: 'Track 5' },
		{ id: 6, label: 'Track 6' },
		{ id: 7, label: 'Track 7' },
		{ id: 8, label: 'Track 8' },
		{ id: 9, label: 'Track 9' },
		{ id: 10, label: 'Track 10' },
		{ id: 11, label: 'Track 11' },
		{ id: 12, label: 'Track 12' },
		{ id: 13, label: 'Track 13' },
		{ id: 14, label: 'Track 14' },
		{ id: 15, label: 'Track 15' },
		{ id: 16, label: 'Track 16' },
		{ id: 17, label: 'Track 17' },
		{ id: 18, label: 'Track 18' },
		{ id: 19, label: 'Track 19' },
		{ id: 20, label: 'Track 20' },
		{ id: 21, label: 'Track 21' },
		{ id: 22, label: 'Track 22' },
		{ id: 23, label: 'Track 23' },
		{ id: 24, label: 'Track 24' },
		{ id: 25, label: 'Track 25' },
		{ id: 26, label: 'Track 26' },
		{ id: 27, label: 'Track 27' },
		{ id: 28, label: 'Track 28' },
		{ id: 29, label: 'Track 29' },
		{ id: 30, label: 'Track 30' },
		{ id: 31, label: 'Track 31' },
		{ id: 32, label: 'Track 32' },
		{ id: 33, label: 'Track 33' },
		{ id: 34, label: 'Track 34' },
		{ id: 35, label: 'Track 35' },
		{ id: 36, label: 'Track 36' },
		{ id: 37, label: 'Track 37' },
		{ id: 38, label: 'Track 38' },
		{ id: 39, label: 'Track 39' },
		{ id: 40, label: 'Track 40' },
		{ id: 41, label: 'Track 41' },
		{ id: 42, label: 'Track 42' },
		{ id: 43, label: 'Track 43' },
		{ id: 44, label: 'Track 44' },
		{ id: 45, label: 'Track 45' },
		{ id: 46, label: 'Track 46' },
		{ id: 47, label: 'Track 47' },
		{ id: 48, label: 'Track 48' },
		{ id: 49, label: 'Track 49' },
		{ id: 50, label: 'Track 50' },
		{ id: 51, label: 'Track 51' },
		{ id: 52, label: 'Track 52' },
		{ id: 53, label: 'Track 53' },
		{ id: 54, label: 'Track 54' },
		{ id: 55, label: 'Track 55' },
		{ id: 56, label: 'Track 56' },
		{ id: 57, label: 'Track 57' },
		{ id: 58, label: 'Track 58' },
		{ id: 59, label: 'Track 59' },
		{ id: 60, label: 'Track 60' },
		{ id: 61, label: 'Track 61' },
		{ id: 62, label: 'Track 62' },
		{ id: 63, label: 'Track 63' },
		{ id: 64, label: 'Track 64' },
	],
	bitLengthSelect_mode: [
		{ id: '16', label: '16bit' },
		{ id: '24', label: '24bit' },
		{ id: 'FF', label: 'Sense' },
	],
	pause_mode: [
		{ id: '00', label: 'Split' },
		{ id: '01', label: 'No Split' },
		{ id: 'FF', label: 'Sense' },
	],
	audioOverMarketSelect_mode: [
		{ id: '00', label: 'Marker Off' },
		{ id: '01', label: 'Marker On' },
		{ id: 'FF', label: 'Sense' },
	],
	timeInternalMarkerSelect_mode: [
		{ id: '00', label: 'Marker Off' },
		{ id: '01', label: 'Marker On' },
		{ id: 'FF', label: 'Sense' },
	],
	syncUnlockMarkerSelect_mode: [
		{ id: '00', label: 'Marker Off' },
		{ id: '01', label: 'Marker On' },
		{ id: 'FF', label: 'Sense' },
	],
	recFsSelect_mode: [
		{ id: '440000', label: '44.1 kHz' },
		{ id: '480000', label: '48 kHz' },
		{ id: '880000', label: '88.2 kHz' },
		{ id: '960000', label: '96 kHz' },
		{ id: 'FF', label: 'Sense' },
	],
	fileNameSelect_mode: [
		{ id: '00', label: 'Date & Time' },
		{ id: '01', label: 'Folder' },
		{ id: '11', label: 'User Word' },
		{ id: 'FF', label: 'Sense' },
	],
	mediaRemainSense_mode: [
		{ id: '00', label: 'SSD' },
		{ id: '01', label: 'USB' },
	],
	mediaFormat_mode: [
		{ id: '0000', label: 'Quick Format: SSD' },
		{ id: '0100', label: 'Full Format: SSD' },
	],
	auxAssignKeySelect_auxKey: [
		{ id: '01', label: 'AUX 1' },
		{ id: '02', label: 'AUX 2' },
		{ id: '03', label: 'AUX 3' },
		{ id: '04', label: 'AUX 4' },
		{ id: '05', label: 'AUX 5' },
		{ id: '06', label: 'AUX 6' },
	],
	auxAssignKeySelect_function: [
		{ id: '00', label: 'PLAY/PAUSE' },
		{ id: '01', label: 'PAUSE' },
		{ id: '02', label: 'REC' },
		{ id: '03', label: 'FADER REC' },
		{ id: '04', label: 'FADER START' },
		{ id: '05', label: 'REW' },
		{ id: '06', label: 'F.FWD' },
		{ id: '07', label: 'TAKE SKIP-' },
		{ id: '08', label: 'TAKE SKIP+' },
		{ id: '09', label: 'MARK SKIP-' },
		{ id: '0A', label: 'MARK SKIP+' },
		{ id: '0B', label: 'TAKE/MARK SKIP-' },
		{ id: '0C', label: 'TAKE/MARK SKIP+' },
		{ id: '0D', label: 'MARK' },
		{ id: 'FF', label: 'Sense' },
	],
	auxAssignKeyTallySelect_auxKey: [
		{ id: '01', label: 'AUX 1' },
		{ id: '02', label: 'AUX 2' },
		{ id: '03', label: 'AUX 3' },
		{ id: '04', label: 'AUX 4' },
		{ id: '05', label: 'AUX 5' },
	],
	auxAssignKeyTallySelect_function: [
		{ id: '00', label: 'STOP' },
		{ id: '01', label: 'PLAY' },
		{ id: '02', label: 'PAUSE' },
		{ id: '03', label: 'REC' },
		{ id: '04', label: 'EOM' },
		{ id: '05', label: 'ERROR' },
		{ id: '06', label: 'EOM/ERROR' },
		{ id: 'FF', label: 'Sense' },
	],
	meterPeakHoldTimePreset_mode: [
		{ id: '00', label: 'Hold Time 0s' },
		{ id: '10', label: 'Hold Time 10s' },
		{ id: 'FE', label: 'Hold Time Inf.' },
		{ id: 'FF', label: 'Sense' },
	],
	digitalReferenceLevelPreset_mode: [
		{ id: '09', label: 'Reference Level - 9dB' },
		{ id: '14', label: 'Reference Level -14dB' },
		{ id: '16', label: 'Reference Level -16dB' },
		{ id: '18', label: 'Reference Level -18dB' },
		{ id: '20', label: 'Reference Level -20dB' },
		{ id: 'FF', label: 'Sense' },
	],
	directTrackSearchPreset_mode: [
		{ id: '10', label: 'Stop' },
		{ id: '12', label: 'Play' },
		{ id: '14', label: 'Pause' },
	],
	mechaStatus_feedback: [
		{ id: '00', label: 'No Media' },
		{ id: '10', label: 'Stop' },
		{ id: '11', label: 'Play' },
		{ id: '12', label: 'Ready On (Pause)' },
		{ id: '28', label: 'Cue' },
		{ id: '29', label: 'Review' },
		{ id: '81', label: 'Record' },
		{ id: '82', label: 'Record Ready' },
		{ id: '83', label: 'Information Writing' },
		{ id: 'FF', label: 'Other' },
	],
	errorSense_feedback: [
		{ id: '0-00', label: 'No Error' },
		{ id: '0-01', label: 'Rec Error' },
		{ id: '1-02', label: 'Device Error' },
		{ id: '1-09', label: 'Info Write Error' },
		{ id: '1-FF', label: 'Other Error' },
	],
	cautionSense_feedback: [
		{ id: '0-00', label: 'No Caution' },
		{ id: '0-01', label: 'Media Error' },
		{ id: '1-06', label: 'Media Full' },
		{ id: '1-07', label: 'Take Full' },
		{ id: '1-09', label: 'Digital Unlock' },
		{ id: '1-0B', label: "Can't Rec" },
		{ id: '1-0C', label: 'Write Protected' },
		{ id: '1-0D', label: 'Not Execute' },
		{ id: '1-0F', label: "Can't Edit" },
		{ id: '1-13', label: "Can't Select" },
		{ id: '1-14', label: 'Track Protected' },
		{ id: '1-16', label: 'Name Full' },
		{ id: '1-1E', label: 'Play Error' },
		{ id: '1-FF', label: 'Other Caution' },
	],
	psuError_feedback: [
		{ id: '0701', label: 'PSU Fault' },
		{ id: '0700', label: 'PSU OK' },
	],
}
